# Generated by Django 4.0.2 on 2022-02-11 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_bio', models.TextField()),
                ('about_phone', models.CharField(max_length=12)),
                ('about_email', models.EmailField(max_length=254)),
                ('about_img', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('about_ins', models.CharField(max_length=200)),
                ('about_fb', models.CharField(max_length=200)),
                ('about_zl', models.CharField(max_length=200)),
                ('skill_title', models.CharField(max_length=100)),
                ('skill_progress', models.DecimalField(decimal_places=2, max_digits=3)),
                ('edu_title', models.CharField(max_length=100)),
                ('edu_year', models.DateField()),
                ('edu_schoolname', models.CharField(max_length=100)),
                ('edu_address', models.CharField(max_length=100)),
                ('edu_content', models.TextField()),
                ('exp_title', models.CharField(max_length=100)),
                ('exp_year', models.DateField()),
                ('exp_descript', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
