# Generated by Django 4.0.2 on 2022-02-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='skill_progress',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
