# Generated by Django 4.0.2 on 2022-02-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_profile_skill_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_fb',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_ins',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_zl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_schoolname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='edu_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp_descript',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='exp_year',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_progress',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
