# Generated by Django 4.0.2 on 2022-02-11 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_about_email_alter_profile_about_fb_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_img',
            new_name='image',
        ),
    ]
