# Generated by Django 4.0.2 on 2022-02-11 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_about_img_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='edu_address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu_content',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu_schoolname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edu_year',
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_title', models.CharField(max_length=100, null=True)),
                ('edu_year', models.DateField(null=True)),
                ('edu_schoolname', models.CharField(max_length=100, null=True)),
                ('edu_address', models.CharField(max_length=100, null=True)),
                ('edu_content', models.TextField(null=True)),
                ('prof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
