# Generated by Django 4.0.2 on 2022-02-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_education_profile_remove_experience_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_progress',
            field=models.DecimalField(decimal_places=0, max_digits=3, null=True),
        ),
    ]
