# Generated by Django 4.0.2 on 2022-02-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_skill_skill_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='defaultback.jpg', upload_to='profile_pics'),
        ),
    ]
