# Generated by Django 4.0.2 on 2022-02-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_education_profile_experience_profile_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(related_name='edu', to='user.Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(related_name='exp', to='user.Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(related_name='skill', to='user.Skill'),
        ),
    ]
