# Generated by Django 4.0.2 on 2022-02-12 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_profile_education_alter_profile_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(related_name='profile', to='user.Education'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(related_name='profile', to='user.Experience'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(related_name='profile', to='user.Skill'),
        ),
    ]
