# Generated by Django 4.0.2 on 2022-02-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_education_profile_remove_experience_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='education',
            field=models.ManyToManyField(related_name='profile', to='user.Education'),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.ManyToManyField(related_name='profile', to='user.Experience'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(related_name='profile', to='user.Skill'),
        ),
    ]
