# Generated by Django 4.0.2 on 2022-02-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_profile_education_profile_experience_profile_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill',
        ),
    ]
