# Generated by Django 4.0.2 on 2022-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_profile_about_email_alter_profile_about_fb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(choices=[('admin', 'admin'), ('contributor', 'contributor')], default='visitor', max_length=50),
        ),
    ]
