# Generated by Django 4.0.2 on 2022-02-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tag',
            field=models.CharField(choices=[('admin', 'admin'), ('contributor', 'contributor'), ('visitor', 'visitor')], default='visitor', max_length=50),
        ),
    ]
