# Generated by Django 4.0.2 on 2022-02-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_profile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
