# Generated by Django 4.0.2 on 2022-02-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
