# Generated by Django 4.0.2 on 2022-02-10 06:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0002_alter_writeup_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
