# Generated by Django 4.0.2 on 2022-02-13 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeup', '0003_alter_writeup_date_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writeup', to=settings.AUTH_USER_MODEL),
        ),
    ]
