# Generated by Django 4.0.2 on 2022-02-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0005_writeup_cate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(choices=[('pwnable.kr', 'pwnable.kr'), ('ctf', 'ctf')], default='challenge', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='writeup',
            name='cate',
        ),
        migrations.AddField(
            model_name='writeup',
            name='cate',
            field=models.ManyToManyField(related_name='writeup', to='writeup.Cate'),
        ),
    ]
