# Generated by Django 4.0.2 on 2022-02-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0006_cate_remove_writeup_cate_writeup_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
