# Generated by Django 4.0.2 on 2022-02-13 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeup', '0007_cate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('prerequis', models.TextField()),
                ('content', models.TextField()),
                ('date_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to=settings.AUTH_USER_MODEL)),
                ('cate', models.ManyToManyField(related_name='new', to='writeup.Cate')),
            ],
        ),
    ]
