# Generated by Django 4.0.2 on 2022-02-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0010_remove_cate_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cate',
            name='tag',
            field=models.CharField(default='challenge', max_length=100),
        ),
    ]
