# Generated by Django 4.0.2 on 2022-02-14 13:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0011_alter_cate_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
