# Generated by Django 4.0.2 on 2022-02-14 14:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0012_alter_writeup_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='content_upload',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
