# Generated by Django 4.0.2 on 2022-02-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0013_writeup_content_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writeup',
            name='content',
        ),
    ]
