# Generated by Django 4.0.2 on 2022-02-16 03:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0015_writeup_like_alter_writeup_prerequis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('writeup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmt', to='writeup.writeup')),
            ],
        ),
    ]
