# Generated by Django 4.0.2 on 2022-02-16 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeup', '0016_commment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmt', to=settings.AUTH_USER_MODEL),
        ),
    ]
