# Generated by Django 4.0.2 on 2022-02-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0017_commment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cate',
            name='image',
            field=models.ImageField(default='defaultback.jpg', upload_to='cate'),
        ),
    ]
