# Generated by Django 4.0.2 on 2022-02-21 00:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writeup', '0019_alter_writeup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writeup',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
