# Generated by Django 4.0.2 on 2022-03-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writeup', '0020_alter_writeup_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='writeup',
            name='privacy',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=10),
        ),
    ]
